apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: 795438191363.dkr.ecr.us-east-1.amazonaws.com/my-flask-app:latest
        ports:
        - containerPort: 3000
