name: Build & Push to ECR

on:
  push:
    branches: [main]   # Trigger only when pushing to 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password |
        doaws ecr get-login-password |
        docker login --username AWS --password-stdin 795438191363.dkr.ecr.us-east-1.amazonaws.com


    - name: Build Docker image and tag
      run: |
        COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
        docker build -t ${{ secrets.ECR_REPO_URI }}:latest \
                     -t ${{ secrets.ECR_REPO_URI }}:$COMMIT_SHA .

    - name: Push images to ECR
      run: |
        docker push ${{ secrets.ECR_REPO_URI }}:latest
        docker push ${{ secrets.ECR_REPO_URI }}:$COMMIT_SHA
